### ISSUE TITLE
tqdm.notebook and FigureCanvasAgg.print_jpg() error

### ISSUE THREAD

**Issue by JohannaRahm** [charlesnchr/ERnet-v2#6]
Hi,

I'd like to run ERnet in Colab but am getting errors in the "Inference" -> "Example of using ERnet Transformer on single images"  and "Example of batch processing" section when executing the notebook with the example data.

The first error I get is related to the tqdm module (installed tqdm version = 4.65.0).

![image](https://github.com/charlesnchr/ERnet-v2/assets/48733135/2cb94b2b-b8a1-41c4-a4a9-3bc47d3834eb)

a workaround is to not use tqdm 

```
for imgidx, imgfile in enumerate(imgs):
    ...
for subimgidx in range(img.shape[0]):
    ...
```

instead of 

```
import tqdm
for imgidx, imgfile in enumerate(tqdm.notebook.tqdm(imgs)):
    ...
for subimgidx in tqdm.notebook.tqdm(range(img.shape[0])):
    ...
```

With the workaround the following error appears

![image](https://github.com/charlesnchr/ERnet-v2/assets/48733135/175b020f-519d-4f58-9a3e-4c7a64173e00)

Thanks for having a look!

Best,
Johanna

**Comment by charlesnchr** [comment]
Hi @JohannaRahm,

Thanks for raising this issue and providing detailed context, including the workaround you tried.

I've just pushed an update to the ERnet repository that should address these errors. The issues with the `tqdm` module and the subsequent error you've faced have been addressed in the refactor.

You can access the updated code by re-opening the Colab notebook from the link in the [README](https://github.com/charlesnchr/ERnet-v2/blob/main/README.md) or pulling the latest changes from the repository if you want to try running the notebook locally. With these changes, you should be able to run ERnet on both single images and in batch processing without encountering these issues.

If you're still experiencing problems after this update, please let me know, and I'd be happy to look further into it. Your feedback is invaluable in improving ERnet, and it's much appreciated.
